# Generated by Django 5.2.4 on 2025-07-29 05:56

import blogapp.helper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='', upload_to='', verbose_name=blogapp.helper.get_file_path),
        ),
    ]
